--- 
data: 
  filepath: "test/testdata/test.jsonl"
eda: 
  outdir: "test/testreport"
  report_in_path: "test/report.ipynb"
  report_out_path: "test/report.html"
  test: True
  tids: 
  - !!python/tuple [1234567890000000000, "test/testdata/scientific.jsonl"]
  - !!python/tuple [9876543129875643210, "test/testdata/misinformation.jsonl"]
